config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :stories do
      resources :locations
    end
  end

  root "home#index"

  get 'about', to: 'home#about'
  get 'users/:id/markers', to: 'users#markers'
  get 'users/:id/stories/:id/markers', to: 'stories#markers'

  get 'stories/index', to: 'stories#index'
  get 'users/sign_in/markers', to: 'users#markers'

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode

  belongs_to :story

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :locations

  validates :name, presence: true
  validates :description, presence: true

  def markers
    arr = Array.new
    locations.each do |location|
      arr << [location.name, location.latitude, location.longitude, location.description]
    end
    return arr
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stories
  has_many :locations, through: :stories

  validates :name, uniqueness: true

  def markers
    arr = Array.new
    locations.each do |location|
      arr << [location.name, location.latitude, location.longitude, location.description]
    end
    return arr
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end 

  def markers
    @markers = [["Flatiron School", 40.705866, -74.014056, "A Place To Learn"], ["Yankee Stadium", 40.830406, -73.926088, "ballgame!"]]
    respond_to do |format|
        format.json {render :markers}
    end
  end

  # 40.705866, -74.014056
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :verify_user, only: [:edit, :new, :create, :destroy]

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
    @story = Story.find(params[:story_id])
    @user = User.find(params[:user_id])
  end

  def new
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
    @story = Story.find(params[:story_id])
    @user = User.find(params[:user_id])
  end

  def create
    @location = Location.new(strong_params)
    @story = Story.find(params[:story_id])
    @user = User.find(params[:user_id])
    @location.story_id = @story.id

    respond_to do |format|
      if @location.save
        @story.locations << @location
        format.html { redirect_to edit_user_story_path(@user.id, @story.id), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
        format.js { render "create.js"}
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def markers
    @location = Location.new(strong_params)
    @story = Story.find(params[:story_id])
    @user = User.find(params[:user_id])
  end

  def update
    respond_to do |format|
      if @location.update(strong_params)
        format.html { redirect_to user_path(params[:user_id]), notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
        format.js { render "update.js"}
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to user_path(params[:user_id]), notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def strong_params
      params.require(:location).permit(:name, :address, :latitude, :longitude, :description)
    end

    def verify_user
      if !user_signed_in? || current_user.id.to_s != params[:user_id]
        redirect_to root_path
      end
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :verify_user, only: [:edit, :new, :create, :destroy]

  def index
    @user = current_user
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @story = Story.new
    @user = User.find(params[:user_id])
  end

  def edit
    @story = Story.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def create
    @story = Story.new(strong_params)
    @user = User.find(params[:user_id])
    @story.user_id = @user.id

    respond_to do |format|
      if @story.save
        @user.stories << @story
        format.html { redirect_to new_user_story_location_path(params[:user_id], @story.id), notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, story: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def markers
    @story = Story.find(params[:id])
    @markers = @story.markers
    respond_to do |format|
        format.json {render :markers}
    end
  end

  def update
    respond_to do |format|
      if @story.update(strong_params)
        format.html { redirect_to user_path(params[:user_id]), notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, story: @story }
        format.js { render "update.js"}
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to user_path(params[:user_id]), notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_story
      @story = Story.find(params[:id])
    end

    def strong_params
      params.require(:story).permit(:name, :description, :user_id, :location_id)
    end

    def verify_user
      if !user_signed_in? || current_user.id.to_s != params[:user_id]
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :markers]
  before_action :verify_user, only: [:edit, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @markers = @user.markers      
  end

  def markers
    @markers = @user.markers
    respond_to do |format|
      format.json {render "../views/stories/markers"}
    end
  end

  def create
    @user = User.create(safe_params)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def safe_params
    params.require(:user).permit(:name, :email, :story_id, :location_id)
  end

  def verify_user
    if !user_signed_in? || current_user.id.to_s != params[:user_id]
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
  <div class="users_index">
    <br><h1>About Us</h1><br>

    <p>Cool Story, Bro is an interactive story visualizer where you can read, create, and explore cool stories.<br>
    If you would like to learn more about how the site was created, you can see our source code <a href="https://github.com/aczerepinski/timeline-visualizer">here.</a><br>
    <br>
    Cool Story, Bro was made at the Flatiron School by:<br><br></p>
  </div>

    <div class="about-container">
      <div class="about-block">
        <h3>Adam Czerepinski</h3><br>
        <div class="about-image">
          <img src="https://openmerchantaccount.com/img/adam_csb.jpg" height="250" width="200">
        </div>
        <div class="icons-block">
          <a href="https://twitter.com/adamczerepinski"><img src="https://openmerchantaccount.com/img/csb_twitter.png" height="39" width="39"></a>
          <a href="https://www.linkedin.com/in/adamcz"><img src="https://openmerchantaccount.com/img/csb_in.png" height="42" width="42"></a>
          <a href="https://github.com/aczerepinski"><img src="https://openmerchantaccount.com/img/csb_github.png" height="35" width="35"></a>
        </div>
      </div>

        <div class="about-block">
          <h3>Stefania Sicurelli</h3><br>
          <div class="about-image">
            <img src="https://openmerchantaccount.com/img/stef_csb.jpg" height="250" width="200">
        </div>
          <div class="icons-block">
            <a href="http://www.twitter.com/stef_sic"><img src="https://openmerchantaccount.com/img/csb_twitter.png" height="39" width="39"></a>
            <a href="https://www.linkedin.com/in/stefaniasicurelli"><img src="https://openmerchantaccount.com/img/csb_in.png" height="42" width="42"></a>
            <a href="https://github.com/stefsic"><img src="https://openmerchantaccount.com/img/csb_github.png" height="35" width="35"></a>
          </div>
        </div>

        <div class="about-block">
          <h3>Evan Rosse</h3><br>
          <div class="about-image">
            <img src="https://openmerchantaccount.com/img/evan_csb.jpg" height="250" width="200">
        </div>
          <div class="icons-block">
            <a href="https://twitter.com/flatironschool"><img src="https://openmerchantaccount.com/img/csb_twitter.png" height="39" width="39"></a>
            <a href="https://www.linkedin.com/pub/evan-rosse/31/1a2/363"><img src="https://openmerchantaccount.com/img/csb_in.png" height="42" width="42"></a>
            <a href="https://github.com/evros001"><img src="https://openmerchantaccount.com/img/csb_github.png" height="35" width="35"></a>
          </div>
        </div>
      </div>
  </div>

app/views/home/index.html.erb
<div class="story-title">
  <h1 class="btn-wrapper">Welcome!</h1>
    <p>Cool Story, Bro is an interactive story visualizer where you can create and explore cool stories.</p>
    <p>Click on any <img src="https://openmerchantaccount.com/img/quote_marker.png" id="location-img"> to reveal details about the cool story you are viewing. To explore our cool stories and cool people, use the navigation bar on the left.</p>

  <div class="btn-wrapper">
    <div class="btn btn-custom" role="button" id="hide-story">GOT IT!</div>
  </div>
</div>

<div id="content-container">
  <div id="map-container">
    <div id="map-canvas">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cool Story, Bro</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <link href='https://fonts.googleapis.com/css?family=Lobster|Nunito' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

  <!-- NAVBAR -->
  <center>
  <div id="nav-map-conatiner">
    <div id="nav-container">
      <nav role="navigation" class="navbar navbar-default">

        <a href="/"><img id="logo-img" src="https://openmerchantaccount.com/img/quote_marker_logo.png"></a>

          <div class="navbar-header">
            <div class="navbar-brand">
              <h1>Cool Story, Bro</h1>
            </div>
          </div>

          <div class="blurb">
            Where are all the cool stories, bro?
            Explore the world's cool stories, or share your own!
            <br>
          </div>

          <ul class="nav navbar-nav">
            <li class="hover"><a href="<%= users_path %>">PEOPLE</a></li>
            <li class="hover"><a href="/stories/index">STORIES</a></li>
            <% if user_signed_in? %>
              <li class="hover"><%= link_to "ADD STORY", new_user_story_path(current_user.id) %></li>
              <li class="hover"><%= link_to "DASHBOARD", user_path(current_user.id) %></li>
            <% else %>
              <li class="hover"><%= link_to "ADD STORY", new_user_registration_path %></li>
            <% end %>
            <li class="hover"><a href="/about">ABOUT</a></li>
            <% if user_signed_in? %>
                <li class="hover"><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li class="hover"><%= link_to "LOG IN", new_user_session_path %></li>
                <li class="hover"><%= link_to "REGISTER", new_user_registration_path %></li>
             <% end %>
          </ul>
      </nav>
    <div class="bottom-nav">
      Content © 2015 <br> Adam Czerepinski, Stefania Sicurelli & Evan Rosse
    </div>
    </div>

    </center>

    <!-- FLASH NOTICES -->
    <% if flash[:error] -%>
      <p class='error'><%=h flash[:error] %></p>
    <% elsif flash[:notice] -%>
      <p class='notice'><%=h flash[:notice] %></p>
    <% elsif flash[:alert] -%>
      <p class='alert'><%=h flash[:alert] %></p>
    <% else %>
    <% end -%>

    <%= yield %>

  </div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location, url: user_story_locations_path do |f| %>

  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Location name:" %><br>
    <%= f.text_area :name, size: "60x1" %>
  </div>
  <div class="field">
    <%= f.label :address, "Enter city and state, landmark, or specific address:" %><br>
    <%= f.text_area :address, size: "60x1" %>
  </div>
    <div class="field">
    <%= f.label :description, "Tell us what happened at this location:" %><br>
    <%= f.text_area :description, size: "60x5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/locations/create.js.erb
$('#new-location-message').html('<p style="color:green">Cool location bro!</p>');
$('#location_name').val("");
$('#location_description').val("");
$('#location_address').val("");

app/views/locations/edit.html.erb
<!-- <h1>Edit Location</h1>

<%= form_for @location, url: user_location_path do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  Name your event:<br>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
  Enter address or location of event ("Statue of Liberty" or "123 Bob Street, New York, NY 11223"):<br>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  Enter latitude / longitude (optional):<br>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

app/views/locations/new.html.erb
<div id="content-container">
  <div class="edit_update_container">
    <br>
    <div class="story-steps">
    <h2><span class="inactive-step">Step 1</span> &nbsp &nbsp <span class="active-step">Step 2</span> &nbsp &nbsp <span class="inactive-step">Step 3</span></h2><br>

    <h1>Where did the story take place?</h1><br>

    <p>Your story's locations and what you write about them make the story cool.<br>
      The locations and descriptions that you add will appear as <img src="https://openmerchantaccount.com/img/quote_marker.png" id="location-img"> on the map.<br><br>

    Give your story its first location.</p><br>

    <%= render 'form' %>
    </div>

    <p>In the next step you will have the option to review your story,<br> manage its locations, and share it with the world!</p>
  </div>
  <div id="map-container" class="opacity">
    <div id="map-canvas">
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<h2><%= @location.name %></h2>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

app/views/locations/update.js.erb
$('.update-<%= @location.id %>').html('<p style="color:green">Cool update bro!</p>');

app/views/stories/_form.html.erb
<%= form_for @story, url: user_stories_path do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Story name:" %><br>
    <%= f.text_area :name, size: "60x1", placeholder: "Cool Trip to Hawaii" %><br>

    <%= f.label :description, "Story summary:" %><br>
    <%= f.text_area :description, size: "60x5", placeholder: "Last year I went to Hawaii, land of sharks and lava. It was the coolest vacation ever..." %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<div id="content-container">
  <div class="edit_update_container_stories">
    <div class="row-container">

      <% if @story.locations.length <= 1 %>
        <br><div class="story-steps">
          <h2><span class="inactive-step">Step 1</span> &nbsp &nbsp <span class="inactive-step">Step 2</span> &nbsp &nbsp
          <span class="active-step">Step 3</span></h2>
        </div>
      <% end %>

        <h1>Story Dashboard</h1>

        <div id="link_to_view_story">
          <%= link_to "View Story", user_story_path(@story.user_id, @story.id) %>
        </div>

      <div class="row">
        <div id="review_story_info">
        <div class="col-sm-6 col-xs-12">
            <%= form_for @story, url: user_story_path, remote: true do |f| %>
              <% if @story.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

                  <ul>
                  <% @story.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>


            <div class="field">
                <h2>Review Story Information</h2>
                <%= f.label :name, "Story Name:" %><br>
                <%= f.text_field :name, :size=>"50" %>
              </div>
                <div class="field">
                  <%= f.label :description, "Story Summary:" %><br>
                  <%= f.text_area :description, size:"50x5" %>
                </div>
                <div class="actions">
                  <%= f.submit "Update Name & Description" %>
                </div>
                <div id="notice-goes-here"></div>
              <% end %>
            </div>
          </div>

          <div class="col-sm-6 col-xs-12" id="new-location-form">
          <h2>Add a Location</h2>
          <%= form_for Location.new, url: user_story_locations_path(:user_id => @story.user_id, :story_id => @story.id), remote: true do |f| %>
            <div class="field">
              <%= f.label :name, "Location Name:" %><br>
              <%= f.text_field :name, :size=>"50x1" %>
            </div>
            <div class="field">
              <%= f.label :address, "Location Address:" %><br>
              <%= f.text_area :address, :size=>"50x1" %>
            </div>
            <div class="field">
              <%= f.label :description, "Tell us what happened at this location:" %><br>
              <%= f.text_area :description, size: "50x5"  %>
            </div>
            <div class="actions">
              <%= f.submit "Add New Location" %>
            </div>
            <div id="new-location-message"></div>
          <% end %>

    <div class="line-break"></div>
          </div>
        </div>

        <div id="edit_location">
          <h2>Edit Story Locations</h2>
          <div class="row">
          <% @story.locations.each do |location| %>
            <%= form_for location, url: user_story_location_path(:user_id => location.story.user_id, :story_id => location.story_id, :id => location.id), remote: true do |f| %>
              <div class="col-sm-6 col-xs-12 edit">
                <div class="field">
                  <%= f.label :name, "Location Name:" %><br>
                  <%= f.text_field :name, :size=>"50x1" %>
                </div>
                <div class="field">
                  <div class="field">
                    <%= f.label :address, "Location Address:" %><br>
                    <%= f.text_field :address, :size=>"50x1" %>
                  </div>
                  <%= f.label :description, "What happened:"%><br>
                  <%= f.text_area :description, :size=>"50x5"  %>
                </div>
                <div class="actions">
                <span class="update-<%=location.id%>"></span>
                  <%= f.submit "Update This Location" %>
                </div>
              </div>
            <% end %>

          <% end %>
          </div>
        </div>

    </div>
  </div>

  <div id="map-container" class="opacity">
      <div id="map-canvas">
      </div>
  </div>
</div>

app/views/stories/index.html.erb
<div class="users_index">
  <h1>Explore Cool Stories</h1>

  <ul class="index-list">
    <% @stories.each do |story| %>
      <li><span class="index-name"><%= story.name.upcase %></span> - <span class="index-description">
        by</span> <strong><%= story.user.name %></strong>
      <span class="index-description">
        <br>Summary: <%= story.description %></span><br>
        <% if user_signed_in? && current_user.id == story.user_id %>
          <%= link_to 'Edit Story', edit_user_story_path(story.user_id, story.id) %> |
        <% end %>
      <%= link_to 'View Story', user_story_path(story.user_id, story.id) %>
      </li>
    <% end %>
  </ul>

  <div id="create-story-link">
    <% if user_signed_in? && current_user.id == @user.id %>
      <%= link_to "Create New Story", new_user_story_path(@user.id) %>
    <% end %>
  </div>

</div>

app/views/stories/new.html.erb
<div id="content-container">
  <div class="edit_update_container">
    <br>
    <div class="story-steps">
      <h2><span class="active-step">Step 1</span> &nbsp &nbsp <span class="inactive-step">Step 2 &nbsp &nbsp Step 3</span></h2>
    </div><br>

    <div class="story-steps-title">
      <h1>Begin Your Story!</h1><br>
    </div>

    <div class="story-steps-body">
      <p>Give your story a cool title and summary. Your summary can be anything you want –<br> short, long, sentimental, awful or anything in between.</p><br>
      <p>Just, please make sure it's cool.</p><br>

      <%= render 'form' %>

      <p>In the next step, you'll add some cool locations.</p>
    </div>
  </div>
  <div id="map-container" class="opacity">
    <div id="map-canvas">
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="show-story hidden">
  <div class="btn btn-custom" role="button">SHOW STORY INFO
  </div>
</div>

<div class="story-title">
  <h1 class="btn-wrapper"><%= @story.name %></h1>
    <p class="btn-wrapper"><strong>by: <%= @story.user.name %></strong><br></p>

      <p><%= @story.description %></p>

      <!-- <p>Locations:
      <% @story.locations.each do |location| %>
      <ul class="list-style">
        <li><%= location.name %></li>
      </ul>
      <% end %></p> -->

      <p><% if user_signed_in? && current_user.id == @user.id %>
        <%= link_to 'Edit', edit_user_story_path(@user.id, @story.id) %> |
        <%= link_to "Delete", user_story_path(@user.id, @story.id), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
      <% end %>
    </p>

  <div class="btn-wrapper">
    <div class="btn btn-custom" role="button" id="hide-story">HIDE STORY INFO</div>
  </div>
</div>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

app/views/stories/update.js.erb
// alert("You updated!");
$('#notice-goes-here').html('<p style="color:green">Cool name and description bro!</p>');

app/views/users/index.html.erb
<div class="users_index">
  <h1>Cool People</h1>

  <ul class="index-list">
    <% @users.each do |user| %>

      <li><%= user.name.upcase %><br>

      <span class="index-description">
        <% if user.stories.first %>
          Sample Story: <%= user.stories.first.name %> - <%=user.stories.first.description %><br>
      </span>
        <% else %>

          This user has no stories. Weird.<br></span>
        <% end %>
          <%= link_to "View all of #{user.name.capitalize}'s Stories", user_path(user.id) %>
        </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="show-story hidden">
  <div class="btn btn-custom" role="button">SHOW STORIES
  </div>
</div>

<div class="story-title">
  <h1 class="btn-wrapper"><%= @user.name %>'s Stories</h1>
   <div class="btn-wrapper">
      <p><% @user.stories.each do |story| %>
      <%= story.name %><br>
      <%= link_to "View", user_story_path(@user.id, story.id) %><br>

          <% if user_signed_in? && current_user.id == @user.id %>
             <%= link_to 'Edit', edit_user_story_path(@user.id, story.id) %> |
            <%= link_to "Delete", user_story_path(@user.id, story.id), method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %><br>
          <% end %>
      <% end %></p>
      <% if user_signed_in? && current_user.id == @user.id %>
        <%= link_to "Create a new story!", new_user_story_path(current_user.id) %>
      <% end %>
    </div>

  <div class="btn-wrapper">
    <div class="btn btn-custom" role="button" id="hide-story">HIDE STORIES</div>
  </div>
</div>

<div id="map-container">
  <div id="map-canvas"></div>
</div>